# Top-level configuration
name = "www-atelier13"
main = "src/pages/index.astro"
compatibility_date = "2022-07-12"

workers_dev = false
route = { pattern = "atelier13interiors.com/*", zone_name = "atelier13interiors.com" }

# Cloudflare Pages configuration (optional)
# When deploying with Pages, Wrangler v3 expects a pages_build_output_dir.
# Astro outputs to "dist" by default.
pages_build_output_dir = "./dist"
